project:
  type: website
  render: 
    - "*.qmd"
    - "!exercices/"

website:
  page-navigation: true
  title: "De R Markdown Ã  Quarto pour aller plus loin avec ses publications"
  description: Rencontres R 2023 tutorial sur Quarto

  repo-url: https://github.com/cderv/tuto-quarto-rr-2023
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@chrisderv"

  sidebar:
    background: "#FDC538"
    align: center
    tools:
      - icon: github
        href: https://github.com/cderv/tuto-quarto-rr-2023
        text: "GitHub DÃ©pot"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Accueil
      - href: preparatif.qmd
        text: PrÃ©paratif
      - text: ---
      - href: 1-quarto-kesako/index.qmd
        text: "Quarto: KÃ©sako ?"
      - href: 2-rmd-quarto/index.qmd
        text: "Passer de Rmd Ã  Quarto"
      - href: 3-projets/index.qmd
        text: Travailler en projet
      - href: 4-synthese/index.qmd
        text: SynthÃ¨se
      - href: 5-aller-plus-loin/index.qmd
        text: Pour aller plus loin...

  page-footer:
    right: "Site web construit et publiÃ© avec [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Christophe Dervieux"
    background: "#FDC538"

lang: fr
author: "Christophe Dervieux"
date: "2023-06-21"

revealjs-plugins:
  - attribution

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
  clean-revealjs:
    preview-links: auto
    theme: [default, ../reveal-style.scss]
    transition: fade
    chalkboard: true
    footer: "[ðŸ”— cderv.quarto.pub/tuto-quarto-rr-2023]()"

execute:
  freeze: auto

editor: visual
